timeout: 14400s

steps:

## Clone & checkout the cert-manager repository
- name: gcr.io/cloud-builders/git
  dir: "go/src/github.com/cert-manager/cert-manager"
  entrypoint: bash
  args:
  - -c
  - |
    set -e
    git clone "${_CM_REPO}" . && git checkout "${_CM_REF}"

## Build release artifacts and push to a bucket
- name: 'eu.gcr.io/jetstack-build-infra-images/bazelbuild:${_BUILDER_IMAGE_TAG}'
  dir: "go/src/github.com/cert-manager/cert-manager"
  entrypoint: bash
  args:
  - -c
  - |
    set -eu -o pipefail
    make vendor-go
    make CMREL_KEY="${_KMS_KEY}" RELEASE_TARGET_BUCKET="${_RELEASE_TARGET_BUCKET}" -j1 upload-release
    echo "Wrote to ${_RELEASE_TARGET_BUCKET}"

tags:
- "cert-manager-release-makestage"
- "ref-${_CM_REF}"

substitutions:
  _CM_REF: "master"
  _CM_REPO: "https://github.com/cert-manager/cert-manager.git"
  _KMS_KEY: "projects/cert-manager-release/locations/europe-west1/keyRings/cert-manager-release/cryptoKeys/cert-manager-release-signing-key/cryptoKeyVersions/1"
  _RELEASE_TARGET_BUCKET: "cert-manager-release"
  _BUILDER_IMAGE_TAG: "20220629-ee75d11-4.2.1"

options:
  machineType: n1-highcpu-32
