/*
Copyright 2021 The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package helm

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/google/go-github/v35/github"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/utils/ptr"

	"github.com/cert-manager/release/pkg/release/manifests"
)

const (
	// Some template strings for GitHub commit and PR messages.
	tplCommitMessage = "Add %s"
	tplPRTitle       = "Helm charts for cert-manager staged release: %s"
	tplPRDescription = "This PR was generated by [cmrel](https://github.com/cert-manager/release) for the cert-manager staged release: `%s`."
)

var acceptableGitHubPermissions sets.String

func init() {
	acceptableGitHubPermissions = sets.NewString("write", "admin")
}

type RepositoryManager interface {
	// Check is called immediately after instantiating the RepositoryManager to
	// verify that the supplied GitHub configuration is valid and that the
	// supplied GitHub client has permissions to perform branching, uploading
	// and creating PRs.
	Check(ctx context.Context) error
	// Publish creates a new GitHub branch, uploads all the chart files and then
	// creates a PR to merge those into the main branch for the repository.
	// The PR URl is returned on success.
	Publish(ctx context.Context, releaseName string, charts ...manifests.Chart) (prURL string, err error)
}

type gitHubRepositoryManager struct {
	*GitHubClient
	owner  string
	repo   string
	branch string
}

// NewGitHubRepositoryManager returns a gitHubRepositoryManager which implements
// RepositoryManager to upload Helm charts to a branch in a GitHub repository
// and create a PR.
func NewGitHubRepositoryManager(client *GitHubClient, owner, repo, branch string) RepositoryManager {
	return &gitHubRepositoryManager{
		GitHubClient: client,
		owner:        owner,
		repo:         repo,
		branch:       branch,
	}
}

// Check is documented at RepositoryManager.Check
// Requests the user associated with the current Oauth token and checks whether
// that user has write permission to the configured repository and whether it
// has the repo scope.
func (o *gitHubRepositoryManager) Check(ctx context.Context) (err error) {
	var errs []error
	// FIXME: Rewrite this deferred error handling
	defer func() {
		// Only join errors if we actually accumulated any, and make sure
		// we don't lose a non-nil err that is being returned.
		if len(errs) == 0 {
			return
		}
		if err != nil {
			errs = append(errs, err)
		}
		err = errors.Join(errs...)
	}()

	// NB: Empty user means current logged in user
	user, response, err := o.UsersClient.Get(ctx, "")
	if err != nil {
		return err
	}
	scopes := strings.Split(response.Header.Get("X-Oauth-Scopes"), ",")
	for i, scope := range scopes {
		scopes[i] = strings.TrimSpace(scope)
	}

	if !sets.NewString(scopes...).Has(string(github.ScopeRepo)) {
		errs = append(errs, fmt.Errorf("expected scope %q, got %v", github.ScopeRepo, scopes))
	}
	loginName := user.GetLogin()
	perm, _, err := o.RepositoriesClient.GetPermissionLevel(ctx, o.owner, o.repo, loginName)
	if err != nil {
		var gitHubErr *github.ErrorResponse
		if !errors.As(err, &gitHubErr) {
			return err
		}
		if gitHubErr.Response.StatusCode == http.StatusNotFound {
			errs = append(
				errs,
				fmt.Errorf(
					"repo %q was not found or it is a private repo which is not accessible to user %q: %v",
					o.destination(),
					loginName,
					err,
				),
			)
		}
		return
	}

	actualPermission := perm.GetPermission()
	if !acceptableGitHubPermissions.Has(actualPermission) {
		errs = append(
			errs,
			fmt.Errorf(
				"expected permission to be one of %q, got: %q",
				strings.Join(acceptableGitHubPermissions.List(), ","),
				actualPermission,
			),
		)
	}

	// Verify that the given branch name can be resolved to a Git ref
	_, _, err = o.GitClient.GetRef(ctx, o.owner, o.repo, fmt.Sprintf("refs/heads/%s", o.branch))
	if err != nil {
		var gitHubErr *github.ErrorResponse
		if !errors.As(err, &gitHubErr) {
			return err
		}
		if gitHubErr.Response.StatusCode == http.StatusNotFound {
			errs = append(errs, fmt.Errorf("branch %q not found: %v", o.branch, err))
		}
	}

	return
}

// Publish is documented at RepositoryManager.Publish
func (o *gitHubRepositoryManager) Publish(ctx context.Context, releaseName string, charts ...manifests.Chart) (string, error) {
	log.Printf("Creating PR for merging Helm charts of %q into %q", releaseName, o.destination())

	// Create a new branch
	newBranchName := releaseName
	ref, err := o.createBranch(ctx, o.branch, newBranchName)
	if err != nil {
		return "", err
	}

	// Upload charts
	for _, chart := range charts {
		if err := o.commitChartToBranch(ctx, ref, chart); err != nil {
			return "", err
		}
	}
	// Create PR
	npr := &github.NewPullRequest{
		Title: ptr.To(fmt.Sprintf(tplPRTitle, releaseName)),
		Body:  ptr.To(fmt.Sprintf(tplPRDescription, releaseName)),
		Base:  ptr.To(o.branch),
		Head:  ptr.To(newBranchName),
	}
	pr, _, err := o.PullRequestClient.Create(ctx, o.owner, o.repo, npr)
	if err != nil {
		return "", err
	}
	prURL := pr.GetHTMLURL()
	log.Printf("Created PR: %s ", prURL)
	return prURL, nil
}

// createBranch creates a new branch on the target repo
// See https://stackoverflow.com/questions/9506181/github-api-create-branch
func (o *gitHubRepositoryManager) createBranch(ctx context.Context, sourceName, branchName string) (*github.Reference, error) {
	baseRef, _, err := o.GitClient.GetRef(ctx, o.owner, o.repo, fmt.Sprintf("refs/heads/%s", sourceName))
	if err != nil {
		return nil, err
	}

	newRef := &github.Reference{
		Ref:    ptr.To(fmt.Sprintf("refs/heads/%s", branchName)),
		Object: baseRef.GetObject(),
	}

	ref, _, err := o.GitClient.CreateRef(ctx, o.owner, o.repo, newRef)
	return ref, err
}

// commitChartToBranch uploads a single Helm chart to the target branch, along with its signature if such a signature exists
func (o *gitHubRepositoryManager) commitChartToBranch(ctx context.Context, ref *github.Reference, chart manifests.Chart) error {
	entries := []*github.TreeEntry{}

	chartFileName := chart.PackageFileName()

	chartContent, err := os.ReadFile(chart.Path())
	if err != nil {
		return err
	}

	// we can't just append a github.TreeEntry because the tgz file is binary data and can't be string encoded, which
	// is required for the "TreeEntry.Content" field. Instead, we have to create a blob manually and use "TreeEntry.SHA"
	// to refer to that blob
	chartBlob, _, err := o.GitClient.CreateBlob(ctx, o.owner, o.repo, &github.Blob{
		Content:  github.String(base64.StdEncoding.EncodeToString(chartContent)),
		Encoding: github.String("base64"),
	})
	if err != nil {
		return err
	}

	entries = append(entries, &github.TreeEntry{
		Path: github.String("charts/" + chartFileName),
		Type: github.String("blob"),
		SHA:  chartBlob.SHA,
		// 100644 = blob, see https://docs.github.com/en/rest/reference/git#create-a-tree--parameters
		Mode: github.String("100644"),
	})

	commitMessage := fmt.Sprintf(tplCommitMessage, chartFileName)

	provPath := chart.ProvPath()

	if provPath != nil {
		// provPath is the path to the prov file in the cert-manager-manifests bundle,
		// and so we use provPath for reading the content of the file, but we want
		// to use `chartFileName + ".prov"` for the committed file's name
		provFileName := chartFileName + ".prov"
		provContent, err := os.ReadFile(*provPath)
		if err != nil {
			return err
		}

		// TreeEntries can create a blob entry if it contains textual data; a prov file does, so
		// it's simpler to add than the tarred + gzipped chart
		entries = append(entries, &github.TreeEntry{
			Path:    github.String("charts/" + provFileName),
			Type:    github.String("blob"),
			Content: github.String(string(provContent)),
			// 100644 = blob, see https://docs.github.com/en/rest/reference/git#create-a-tree--parameters
			Mode: github.String("100644"),
		})

		commitMessage = commitMessage + fmt.Sprintf(" and %s", provFileName)
	}

	tree, _, err := o.GitClient.CreateTree(ctx, o.owner, o.repo, *ref.Object.SHA, entries)
	if err != nil {
		return err
	}

	parent, _, err := o.RepositoriesClient.GetCommit(ctx, o.owner, o.repo, *ref.Object.SHA)
	if err != nil {
		return err
	}

	// This needs to be set, according to:
	// https://github.com/google/go-github/blob/d1fa419b36aa9b7c70bc3464609991555667f681/example/commitpr/main.go#L132
	parent.Commit.SHA = parent.SHA

	commit := &github.Commit{
		// nil author fills in with authenticated user details + current date
		Author:  nil,
		Message: &commitMessage,
		Tree:    tree,
		Parents: []*github.Commit{parent.Commit},
	}
	newCommit, _, err := o.GitClient.CreateCommit(ctx, o.owner, o.repo, commit)
	if err != nil {
		return err
	}

	ref.Object.SHA = newCommit.SHA
	_, _, err = o.GitClient.UpdateRef(ctx, o.owner, o.repo, ref, false)
	if err != nil {
		return err
	}

	return nil
}

func (o *gitHubRepositoryManager) destination() string {
	return fmt.Sprintf("github.com/%s/%s@%s", o.owner, o.repo, o.branch)
}
